### ISSUE TITLE
Poller executes extra GET request if original request is PUT/PATCH

### ISSUE THREAD

**Issue by gracewilcox** [Azure/azure-sdk-for-go#19889]
When a poller PUT/PATCH request finishes and calls the poller async Result method, it'll execute a final GET request to the original URL. 

This causes an error in some cases. If you send a GET request to the URL I am currently working with, it will cause a `400 Bad Argument` error since the service was expecting a PUT request with a body. In this case, the code shouldn't send that final GET request.

Line of code in Poller: [here](https://github.com/Azure/azure-sdk-for-go/blob/73e2c0181e0c671247d301c5e2e1c9b8fe736f32/sdk/azcore/internal/pollers/async/async.go#L132)

**Comment by jhendrixMSFT** [comment]
Per the [docs](https://github.com/Azure/autorest/tree/main/docs/extensions#x-ms-long-running-operation) a `final-state-via` value of `azure-async-operation` does _not_ require a final GET.

**Comment by tadelesh** [comment]
I've tested some API in control plane. One example [here](https://github.com/Azure/azure-rest-api-specs/blob/78ec1b99699a4bf44869bd13f1b0ed7d92a99c27/specification/network/resource-manager/Microsoft.Network/stable/2022-07-01/applicationSecurityGroup.json#L145). The return from the last call of `Azure-AsyncOperation` URI does not contain the resource info and it will cause empty return of `CreateOrUpdate`. Log as follows.

[Jan 30 13:06:08.412480] Request: ==> OUTGOING REQUEST (Try=1)
   PUT https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/chenjieshitest/providers/Microsoft.Network/applicationSecurityGroups/test-asg2?api-version=2022-07-01
   Accept: application/json
   Authorization: REDACTED
   Content-Length: 21
   Content-Type: application/json
   User-Agent: azsdk-go-armnetwork/v2.1.0 (go1.19; Windows_NT)
   --------------------------------------------------------------------------------
{"location":"eastus"}
   --------------------------------------------------------------------------------
[Jan 30 13:06:15.911467] Response: ==> REQUEST/RESPONSE (Try=1/7.4990073s, OpTime=7.4990589s) -- RESPONSE RECEIVED
   PUT https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/chenjieshitest/providers/Microsoft.Network/applicationSecurityGroups/test-asg2?api-version=2022-07-01
   Accept: application/json
   Authorization: REDACTED
   Content-Length: 21
   Content-Type: application/json
   User-Agent: azsdk-go-armnetwork/v2.1.0 (go1.19; Windows_NT)
   --------------------------------------------------------------------------------
   RESPONSE Status: 201 Created
   Azure-Asyncnotification: Enabled
   Azure-Asyncoperation: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Network/locations/eastus/operations/e5ec5b78-ac57-49ff-8e97-eeb7becae557?api-version=2022-07-01
   Cache-Control: no-cache
   Content-Length: 387
   Content-Type: application/json; charset=utf-8
   Date: Mon, 30 Jan 2023 05:06:14 GMT
   Expires: -1
   Pragma: no-cache
   Retry-After: 10
   Server: Microsoft-HTTPAPI/2.0
   Strict-Transport-Security: REDACTED
   X-Content-Type-Options: REDACTED
   X-Ms-Arm-Service-Request-Id: REDACTED
   X-Ms-Correlation-Request-Id: REDACTED
   X-Ms-Ratelimit-Remaining-Subscription-Writes: REDACTED
   X-Ms-Request-Id: e5ec5b78-ac57-49ff-8e97-eeb7becae557
   X-Ms-Routing-Request-Id: REDACTED
   --------------------------------------------------------------------------------
{
  "name": "test-asg2",
  "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/chenjieshitest/providers/Microsoft.Network/applicationSecurityGroups/test-asg2",
  "etag": "W/\"5d6524db-40ee-4d27-9c95-8b03f13c7288\"",
  "type": "Microsoft.Network/applicationSecurityGroups",
  "location": "eastus",
  "properties": {
    "provisioningState": "Updating"
  }
}
   --------------------------------------------------------------------------------

[Jan 30 13:06:15.911467] Retry: response 201
[Jan 30 13:06:15.911467] Retry: exit due to non-retriable status code
[Jan 30 13:06:15.911986] LongRunningOperation: Using Azure-AsyncOperation poller.
[Jan 30 13:06:15.912133] LongRunningOperation: BEGIN PollUntilDone() for *async.Poller[github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v2.ApplicationSecurityGroupsClientCreateOrUpdateResponse]
[Jan 30 13:06:15.912133] LongRunningOperation: initial Retry-After delay for 10s
[Jan 30 13:06:25.920669] Retry: =====> Try=1
[Jan 30 13:06:25.920669] Request: ==> OUTGOING REQUEST (Try=1)
   GET https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Network/locations/eastus/operations/e5ec5b78-ac57-49ff-8e97-eeb7becae557?api-version=2022-07-01
   Authorization: REDACTED
   User-Agent: azsdk-go-armnetwork/v2.1.0 (go1.19; Windows_NT)
   Request contained no body
[Jan 30 13:06:26.907477] Response: ==> REQUEST/RESPONSE (Try=1/986.8113ms, OpTime=986.8113ms) -- RESPONSE RECEIVED
   GET https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Network/locations/eastus/operations/e5ec5b78-ac57-49ff-8e97-eeb7becae557?api-version=2022-07-01
   Authorization: REDACTED
   User-Agent: azsdk-go-armnetwork/v2.1.0 (go1.19; Windows_NT)
   --------------------------------------------------------------------------------
   RESPONSE Status: 200 OK
   Cache-Control: no-cache
   Content-Type: application/json; charset=utf-8
   Date: Mon, 30 Jan 2023 05:06:26 GMT
   Expires: -1
   Pragma: no-cache
   Server: Microsoft-HTTPAPI/2.0
   Strict-Transport-Security: REDACTED
   Vary: REDACTED
   X-Content-Type-Options: REDACTED
   X-Ms-Arm-Service-Request-Id: REDACTED
   X-Ms-Correlation-Request-Id: REDACTED
   X-Ms-Ratelimit-Remaining-Subscription-Reads: REDACTED
   X-Ms-Request-Id: f369b507-d329-466e-9db3-b4e3b16bb89a
   X-Ms-Routing-Request-Id: REDACTED
   --------------------------------------------------------------------------------
{
  "status": "Succeeded"
}
   --------------------------------------------------------------------------------

[Jan 30 13:06:26.908002] Retry: response 200
[Jan 30 13:06:26.908002] Retry: exit due to non-retriable status code
[Jan 30 13:06:26.908091] LongRunningOperation: State Succeeded
[Jan 30 13:06:26.908164] LongRunningOperation: END PollUntilDone() for *async.Poller[github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v2.ApplicationSecurityGroupsClientCreateOrUpdateResponse]: succeeded, total time: 10.9959881s
[Jan 30 13:06:28.749015] Retry: =====> Try=1
[Jan 30 13:06:28.749015] Request: ==> OUTGOING REQUEST (Try=1)
   GET https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/chenjieshitest/providers/Microsoft.Network/applicationSecurityGroups/test-asg2?api-version=2022-07-01
   Authorization: REDACTED
   User-Agent: azsdk-go-armnetwork/v2.1.0 (go1.19; Windows_NT)
   Request contained no body
[Jan 30 13:06:29.951970] Response: ==> REQUEST/RESPONSE (Try=1/1.2029584s, OpTime=1.2029584s) -- RESPONSE RECEIVED
   GET https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/chenjieshitest/providers/Microsoft.Network/applicationSecurityGroups/test-asg2?api-version=2022-07-01
   Authorization: REDACTED
   User-Agent: azsdk-go-armnetwork/v2.1.0 (go1.19; Windows_NT)
   --------------------------------------------------------------------------------
   RESPONSE Status: 200 OK
   Cache-Control: no-cache
   Content-Type: application/json; charset=utf-8
   Date: Mon, 30 Jan 2023 05:06:29 GMT
   Etag: W/"6ef7c270-3763-4dcd-8ad2-4dc4cd78513a"
   Expires: -1
   Pragma: no-cache
   Server: Microsoft-HTTPAPI/2.0
   Strict-Transport-Security: REDACTED
   Vary: REDACTED
   X-Content-Type-Options: REDACTED
   X-Ms-Arm-Service-Request-Id: REDACTED
   X-Ms-Correlation-Request-Id: REDACTED
   X-Ms-Ratelimit-Remaining-Subscription-Reads: REDACTED
   X-Ms-Request-Id: 9476fd57-ec6a-43b1-9660-5ba5a0d84356
   X-Ms-Routing-Request-Id: REDACTED
   --------------------------------------------------------------------------------
{
  "name": "test-asg2",
  "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/chenjieshitest/providers/Microsoft.Network/applicationSecurityGroups/test-asg2",
  "etag": "W/\"6ef7c270-3763-4dcd-8ad2-4dc4cd78513a\"",
  "type": "Microsoft.Network/applicationSecurityGroups",
  "location": "eastus",
  "properties": {
    "provisioningState": "Succeeded"
  }
}
   --------------------------------------------------------------------------------

[Jan 30 13:06:29.951970] Retry: response 200
[Jan 30 13:06:29.951970] Retry: exit due to non-retriable status code

**Comment by tadelesh** [comment]
Thanks @gracewilcox. I'll double check with ARM about the `Azure-AsyncOperation` behavior.

**Comment by jhendrixMSFT** [comment]
Maybe we can fix this in such a way that for ARM we preserve the original behavior.

**Comment by RickWinter** [comment]
This is concerning that we are intentionally not implementing the spec into autorest.go b/c some services failed to correctly follow/implement the spec in the service.  I agree with Joel that the swaggers which are wrong should be fixed.

cc: @JeffreyRichter , @mikekistler

**Comment by jhendrixMSFT** [comment]
Thinking about this more, even if we were to fix all of them, we still have a compat problem.  E.g. if we fix this in `azcore` and customers don't pick up the fixes in their `arm*` packages they will be broken (this is effectively a runtime breaking change).

**Comment by JeffreyRichter** [comment]
This is a very complex problem. The LRO guidance was poor before, and different service teams interpreted differently with slightly different implementations. Then, to draw a lilnk between initiating and polling operations, autorest defined some "enhancements" because there is no standard REST pattern here. But, these enhancements are not standard/consistently applied, and code generators made assumptions. Joel can attest to how complicated this is.

So, then the stewardship board addressed this and came up with really clear LRO patterns that make less assumptions and require less magic. New (data-plane) services should follow this but ARM maintains some "consistency" with the past. 

Autorest now has multiple patterns to contend with and we can't break/change how services work. 
Go could have ignored part of the original/old/bad pattern (because it has race conditions associated with it) but we didn't do this and now it is breaking to implement this change.

It would be great to fix old swaggers but I dont know how practicle this is. @mikekistler can speak to this better than I can.

**Comment by mikekistler** [comment]
This is a very complex problem.

But it seems that there are multiple problems.  Joel is talking about changes to Azure.Core.  But we are also talking about changing REST API definitions to be "correct" so that we generate the right code.

Are both of these needed?

Said another way: is it _impossible_ to generate correct (working) code from a correct REST API definition without changing Azure Core?

**Comment by jhendrixMSFT** [comment]
It's even more nuanced than that.  The crux of the problem is that our `Azure-AsyncOperation` (AAO) poller, which lives in `azcore`, assumes the RELO pattern for ARM when the HTTP verb is `PATCH` or `PUT`.  On top of that, there are various ARM specs that are incorrect in their LRO authoring (see the example above); this doesn't become a problem in practice due to our RELO assumptions.  There was also a (bad) assumption early on that the AAO pattern was limited to ARM.

Now, we have a data-plane service (keyvault) using the AAO pattern that _is_ following the spec and is not a RELO.  Unfortunately, our AAO poller can't cope with this.

**Comment by jhendrixMSFT** [comment]
We _might_ be able to fix this at runtime by examining the host URL.  If it's a management endpoint, then we use the broken behavior.  Needs further investigation.

**Comment by jhendrixMSFT** [comment]
Per discussion, `final-state-via` is for `POST` only. The docs have been updated, see https://github.com/Azure/autorest/pull/5004.
