### ISSUE TITLE
Make the `eng/tools/generator` support data plane packages

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#23820]
The generator tool in `eng/tools/generator` is run in azure-rest-api-specs when you make a change. Currently, it makes some reasonable assumptions that you're working on an ARM package, so there are some checks that need to be relaxed or changed to properly work for data plane. This came up when I tried to merge in a change for tspconfig.yaml in EventGrid Namespaces: https://github.com/Azure/azure-rest-api-specs/pull/31719.

We were having a discussion in a (now merged) PR so I wanted to move it here so we can track it, and track any work that might result from that discussion.

[(previous comment)](https://github.com/Azure/azure-sdk-for-go/pull/23815#pullrequestreview-2474581382)

> the generator tool previously only implemented for control plane package generation, thus cause the ci failure. i don't know whether we should enable sdk automation for typespec for go data plane. @lirenhe thoughts? but this pr lgtm, it could at least unblock the pr merge.

**Comment by lirenhe** [comment]
As the SDK automation would only be triggered when service team configured tspconfig.yaml, I suggest we enable it for data plane as well but limited the scope for only typespec input,  suggestions?

**Comment by tadelesh** [comment]
make sense. since sdk automation for go is required in ci check. we need to go through all the codes related with sdk automation and add data plane support. i'll let vendor to follow up first.

**Comment by richardpark-msft** [comment]
CC: @jhendrixMSFT, @gracewilcox, @chlowell 

Just FYI, there is automation in azure-rest-api-specs that fails, today, on data-plane packages. I just filed this issue to track it.

**Comment by tadelesh** [comment]
resolved by: https://github.com/Azure/azure-sdk-for-go/pull/23879

**Comment by richardpark-msft** [comment]
@tadelesh, @jliusan

I'm trying to merge in a change to the Event Grid Namespaces project and our Go step is still failing: [PR run step failure](https://github.com/Azure/azure-rest-api-specs/pull/32010/checks?check_run_id=35226522435).

The log output doesn't say what the error is, only that it failed:

```log
command	sh ./eng/scripts/automation_init.sh ../../../../../azure-sdk-for-go_tmp/initInput.json ../../../../../azure-sdk-for-go_tmp/initOutput.json
command	generator automation-v2 ../../../../../azure-sdk-for-go_tmp/generateInput.json ../../../../../azure-sdk-for-go_tmp/generateOutput.json
cmdout	[Go] Start to process typespec project: specification/eventgrid/Azure.Messaging.EventGrid.SystemEvents
error	Script return with result [failed] code [2] signal [null] cwd [azure-sdk-for-go/src/github.com/Azure/azure-sdk-for-go]: generator automation-v2
warn	Warning: File azure-sdk-for-go_tmp/generateOutput.json not found to read. Please re-run the pipeline if the error is transitient error or report this issue through https://aka.ms/azsdk/support/specreview-channel.
warn	Warning: Package processing is skipped as the SDK generation fails. Please look into the above generation errors or report this issue through https://aka.ms/azsdk/support/specreview-channel.
```

Is there something I need to do to properly opt-in or is there something broken in the change?

**Comment by tadelesh** [comment]
@richardpark-msft i just realized that you need to config `service-dir` and `package-dir` explicitly like the mgmt. plane config in `tspconfig.yaml`. it is used by `tsp-client` to identify the package dir under our sdk repo. refer this: https://github.com/Azure/azure-rest-api-specs/blob/b6075dbc2321933382ea91c787ee62c6bdb87e5d/specification/contosowidgetmanager/Contoso.Management/tspconfig.yaml#L41-L42.

**Comment by richardpark-msft** [comment]
@tadelesh - thank you for the help on all of this. I'll update the tsp-config for now, we can discuss if we want to infer it at some point.
